"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let myName = "abdul_rehman";
let age = 23;
let number = [0, 1, 2, 3, 4, 5];
console.log("Is myName == abdul_rehman? I predict that's True");
console.log(myName == "abdul_rehman");
console.log("Ts myName === Abdul_Rehman? I predict that's False");
console.log(myName === "Abdul_Rehman");
console.log("Is myName!= Abdul_Rehman? I predict that's True");
console.log(myName != "Abdul_Rehman");
console.log("myName!== abdul_rehman? I predict that's False");
console.log(myName !== "abdul_rehman");
console.log("Is myName.toLowerCase() == abdul_rehman? I predict that's True");
console.log(myName.toLowerCase() == "abdul_rehman");
console.log("Is myName.toLowerCase() === Abdul_Rehman? I predict that's False");
console.log(myName.toLowerCase() === "Abdul_Rehman");
console.log("Is age == 23? I predict that's True");
console.log(age == 23);
console.log("Is age === 24? I predict that's False");
console.log(age === 24);
console.log("Is age != 25? I predict that's True");
console.log(age != 25);
console.log("Is age !== 23? I predict that's False");
console.log(age !== 23);
console.log("Is age < 25? I predict that's True");
console.log(age < 25);
console.log("Is age > 25? I predict that's False");
console.log(age > 25);
console.log("Is age <= 25? I predict that's True");
console.log(age <= 25);
console.log("Is age >= 25? I predict that's False");
console.log(age >= 25);
console.log("36>age && 23==age? I predict that's True");
console.log(36 > age && 23 == age);
console.log("age>33 || age>44? I predict that's False");
console.log(age > 33 || age > 44);
console.log("number.includes(5)? I predict that's True");
console.log(number.includes(5));
console.log("number.includes(55)? I predict that's False");
console.log(number.includes(55));
