"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let car = 'Subaru';
let a = 5;
let b = 15;
console.log("is car == 'Subaru'? I predict True.");
console.log(car == 'Subaru');
console.log("is car === 'Subaru'? I predict True.");
console.log(car === 'Subaru');
console.log("is car != 'Subaru'? I predict False.");
console.log(car != 'Subaru');
console.log("is car !== 'Subaru'? I predict False.");
console.log(car !== 'Subaru');
console.log("is a < b? I predict True.");
console.log(a < b);
console.log("is a > b? I predict False.");
console.log(a > b);
console.log("is a <= b? I predict True.");
console.log(b <= b);
console.log("is a >= a? I predict True.");
console.log(a >= a);
console.log("is car || 'subaru'? I predict");
console.log(car && 'subaru');
console.log("is car? I predict True.");
console.log(car);
